apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: cmvolume
  name: cmvolume
spec:
  containers:
  - image: nginx
    name: cmvolume
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
