apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multi
  name: multi
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - echo hello;sleep 3600
    image: busybox
    name: c1
  - command:
    - /bin/sh
    - -c
    - echo hello;sleep 3600
    image: busybox
    name: c2
