apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
spec:
  volumes:
  - name: shared
    emptyDir: {}
  containers:
  - image: busybox
    name: busybox
    command:
    - /bin/sh
    - -c
    - sleep 3600
    volumeMounts:
    - name: shared
      mountPath: /etc/foo
  - image: busybox
    name: busybox2
    command:
    - /bin/sh
    - -c
    - sleep 3600 
    volumeMounts:
    - name: shared
      mountPath: /etc/foo
