apiVersion: v1
kind: Pod
metadata:
  name: pv-pod2
spec:
  volumes:
  - name: storage 
    persistentVolumeClaim:
      claimName: mypvc
  containers:
  - name: busybox 
    image: busybox
    volumeMounts:
    - mountPath: "/etc/foo/passwd"
      name: storage
    command:
    - /bin/sh
    - -c
    - sleep 3600
