apiVersion: v1
kind: PersistentVolume
metadata:
  name: myvolume
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  storageClassName: normal
  hostPath:
    path: /etc/foo
  capacity:
    storage: 10Gi
