apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: myapp-v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      version: v1
  template:
    metadata:
      labels:
        app: myapp
        version: v1
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: workdir
          mountPath: "/usr/share/nginx/html"
      initContainers:
      - image: busybox
        name: install
        volumeMounts:
        - name: workdir
          mountPath: "/work-dir"
        command:
        - /bin/sh
        - -c
        - "echo version-1 > /work-dir/index.html"
      volumes:
      - name: workdir
        emptyDir: {}
