apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: gpu
  name: gpu
spec:
  nodeSelector:
    accelerator: nvidia-tesla-p100
  containers:
  - image: nginx
    name: gpu
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
